apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turn-stage

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/ilhamzefer-sketch/turn-ui
    newTag: 1bcac1117070abd0f700e2e1d1ff3b0d806eac5a
