apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turn-stage

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/ilhamzefer-sketch/turn-ui
    newTag: eb308c866ba2868a1de923116ece2d3241c04ec8
