apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turn-stage

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/ilhamzefer-sketch/turn-ui
    newTag: 735c76d7337d50473bc36d549883cfa328abe41a
