import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Link } from "react-router-dom";

import { stepSixApi } from "../../shared/api/stepSixApi";
import { usePageMeta } from "../../shared/meta/usePageMeta";
import { Button } from "../../shared/ui/Button";
import { SelectField } from "../../shared/ui/SelectField";
import { TextAreaField } from "../../shared/ui/TextAreaField";

export function AdminPlatformPage() {
  usePageMeta("Platform idarəetməsi — NövbəTime", "NövbəTime platforma əməliyyatları.", { index: false });
  const overview = useQuery({ queryKey: ["admin-overview"], queryFn: stepSixApi.adminOverview, retry: false });
  const disputes = useQuery({ queryKey: ["admin-disputes"], queryFn: stepSixApi.adminDisputes, enabled: overview.isSuccess });
  const phone = useQuery({ queryKey: ["admin-phone-changes"], queryFn: stepSixApi.adminPhoneChanges, enabled: overview.isSuccess });
  const deletions = useQuery({ queryKey: ["admin-deletions"], queryFn: stepSixApi.adminDeletions, enabled: overview.isSuccess });
  if (overview.isPending) return <main className="admin-platform shell" role="status">Platform məlumatları açılır…</main>;
  if (overview.isError) return <main className="admin-platform shell"><h1>Admin sessiyası tələb olunur</h1><p>{overview.error.message}</p><Link className="button" to="/platform/login">Admin girişinə keç</Link></main>;
  const data = overview.data;
  return <main className="admin-platform shell"><header className="insight-header"><div><p className="eyebrow">Platform admin</p><h1>Platformanın ümumi vəziyyəti</h1><p>Support qərarları auditlidir. Biznes əməliyyatlarını biznes sahibinin yerinə idarə etmir.</p></div></header><section className="metric-grid"><AdminMetric label="İstifadəçilər" value={data.users} /><AdminMetric label="Bizneslər" value={data.businesses} /><AdminMetric label="Otaqlar" value={data.rooms} /><AdminMetric label="Aktiv abunəlik" value={data.activeSubscriptions} /></section><div className="insight-grid"><section className="insight-panel"><h2>Hesab vəziyyəti</h2><dl className="detail-list"><div><dt>Aktiv istifadəçi</dt><dd>{data.activeUsers}</dd></div><div><dt>Dayandırılan</dt><dd>{data.suspendedUsers}</dd></div><div><dt>Güzəşt abunəliyi</dt><dd>{data.graceSubscriptions}</dd></div><div><dt>Dayandırılan abunəlik</dt><dd>{data.suspendedSubscriptions}</dd></div></dl></section><section className="insight-panel"><h2>Açıq müraciətlər</h2><dl className="detail-list"><div><dt>Sahiblik mübahisəsi</dt><dd>{data.openOwnershipDisputes}</dd></div><div><dt>Telefon dəyişikliyi</dt><dd>{data.openPhoneChanges}</dd></div><div><dt>Hesab silinməsi</dt><dd>{data.openDeletionRequests}</dd></div><div><dt>Tamamlanan ödəniş</dt><dd>{data.completedSubscriptionPayments}</dd></div></dl></section></div><section className="insight-panel"><p className="eyebrow">Manual yoxlama</p><h2>Support növbəsi</h2><div className="admin-case-list">{disputes.data?.filter((item) => item.status === "OPEN" || item.status === "IN_REVIEW").map((item) => <DisputeCase key={item.id} item={item} onDone={() => disputes.refetch()} />)}{phone.data?.filter((item) => item.status === "OPEN" || item.status === "IN_REVIEW").map((item) => <SimpleCase key={`p-${item.id}`} title={`Telefon dəyişikliyi #${item.id}`} detail={`${item.currentPhone} → ${item.requestedPhone} · ${item.reason}`} onResolve={(approve, note) => stepSixApi.resolvePhoneChange(item.id, approve, note)} onDone={() => phone.refetch()} />)}{deletions.data?.filter((item) => item.status === "OPEN" || item.status === "IN_REVIEW").map((item) => <SimpleCase key={`d-${item.id}`} title={`Hesab silinməsi #${item.id}`} detail={`İstifadəçi #${item.userId}`} onResolve={(approve, note) => stepSixApi.resolveDeletion(item.id, approve, note)} onDone={() => deletions.refetch()} />)}</div></section></main>;
}
function AdminMetric({ label, value }: { label: string; value: number }) { return <article><span>{label}</span><strong>{value}</strong></article>; }
function DisputeCase({ item, onDone }: { item: Awaited<ReturnType<typeof stepSixApi.adminDisputes>>[number]; onDone: () => void }) { const [action, setAction] = useState<"NO_ACTION" | "SUSPEND" | "RESET_PASSWORD" | "RESTORE_ACCESS">("NO_ACTION"); const [note, setNote] = useState(""); const mutation = useMutation({ mutationFn: () => stepSixApi.resolveDispute(item.id, action, note), onSuccess: onDone }); return <article><h3>Sahiblik mübahisəsi #{item.id}</h3><p>{item.disputedPhone} · {item.claimantName} · {item.claimantContactPhone}</p><p>{item.description}</p><SelectField label="Qərar" value={action} onChange={(e) => setAction(e.target.value as typeof action)}><option value="NO_ACTION">Əməliyyat yoxdur</option><option value="SUSPEND">Hesabı dayandır</option><option value="RESET_PASSWORD">Şifrəni sıfırla</option><option value="RESTORE_ACCESS">Girişi bərpa et</option></SelectField><TextAreaField label="Qərarın izahı" value={note} onChange={(e) => setNote(e.target.value)} /><Button disabled={!note.trim()} loading={mutation.isPending} onClick={() => mutation.mutate()}>Qərarı saxla</Button></article>; }
function SimpleCase({ title, detail, onResolve, onDone }: { title: string; detail: string; onResolve: (approve: boolean, note: string) => Promise<unknown>; onDone: () => void }) { const [note, setNote] = useState(""); const mutation = useMutation({ mutationFn: (approve: boolean) => onResolve(approve, note), onSuccess: onDone }); return <article><h3>{title}</h3><p>{detail}</p><TextAreaField label="Qərarın izahı" value={note} onChange={(e) => setNote(e.target.value)} /><div><Button disabled={!note.trim()} loading={mutation.isPending} onClick={() => mutation.mutate(true)}>Təsdiqlə</Button><Button variant="secondary" disabled={!note.trim()} onClick={() => mutation.mutate(false)}>Rədd et</Button></div></article>; }
